**DataSet Generation**

In [133]:
import pandas as pd
import numpy as np
 
np.random.seed(42)
n_rows = 150
data = {
    'Customer_ID': [f'CUST_{1000 + i}' if i % 12 != 0 else np.nan for i in range(n_rows)],
    'Join_Date': pd.date_range(start='2023-01-01', periods=n_rows, freq='2D'),
    'Age': [np.random.randint(18, 65) if i % 7 != 0 else np.nan for i in range(n_rows)],
    'Gender': np.random.choice(['Male', 'Female', 'Other'], size=n_rows, p=[0.48, 0.48, 0.04]),
    'City': np.random.choice(['Karachi', 'Lahore', 'Islamabad', 'Peshawar'], size=n_rows),
    'Category': np.random.choice(['Electronics', 'Clothing', 'Home', 'Books'], size=n_rows),
    'Order_Count': np.random.randint(1, 30, size=n_rows),
    'Total_Spent': [round(np.random.uniform(500, 50000), 2) if i % 9 != 0 else np.nan for i in range(n_rows)],
    'Is_VIP': np.random.choice([True, False], size=n_rows, p=[0.2, 0.8])
}
df = pd.DataFrame(data)
df.head(10)

,Customer_ID,Join_Date,Age,Gender,City,Category,Order_Count,Total_Spent,Is_VIP
0,NaN,2023-01-01,NaN,Male,Karachi,Home,3,NaN,False
1,CUST_1001,2023-01-03,56.0,Male,Peshawar,Home,17,16472.98,False
2,CUST_1002,2023-01-05,46.0,Female,Peshawar,Electronics,3,2648.34,True
3,CUST_1003,2023-01-07,32.0,Female,Lahore,Books,16,46269.84,False
4,CUST_1004,2023-01-09,60.0,Female,Karachi,Electronics,4,45996.23,False
5,CUST_1005,2023-01-11,25.0,Female,Lahore,Electronics,18,13023.01,True
6,CUST_1006,2023-01-13,38.0,Female,Karachi,Clothing,17,34922.85,False
7,CUST_1007,2023-01-15,NaN,Female,Lahore,Clothing,7,4234.01,False
8,CUST_1008,2023-01-17,56.0,Male,Islamabad,Electronics,24,8727.66,False
9,CUST_1009,2023-01-19,36.0,Male,Peshawar,Home,23,NaN,True

In [134]:
print("Dataset Ready! Total rows:", len(df))

Dataset Ready! Total rows: 150

**ALL TASKS**

In [135]:
print('Data Types: ', df.dtypes)
print('Shape: ', df.shape)
print('Data Types: ', df.isna().sum())

Data Types:  Customer_ID               str
Join_Date      datetime64[us]
Age                   float64
Gender                    str
City                      str
Category                  str
Order_Count             int32
Total_Spent           float64
Is_VIP                   bool
dtype: object
Shape:  (150, 9)
Data Types:  Customer_ID    13
Join_Date       0
Age            22
Gender          0
City            0
Category        0
Order_Count     0
Total_Spent    17
Is_VIP          0
dtype: int64

In [136]:
df = df.dropna(subset='Customer_ID')
df

,Customer_ID,Join_Date,Age,Gender,City,Category,Order_Count,Total_Spent,Is_VIP
1,CUST_1001,2023-01-03,56.0,Male,Peshawar,Home,17,16472.98,False
2,CUST_1002,2023-01-05,46.0,Female,Peshawar,Electronics,3,2648.34,True
3,CUST_1003,2023-01-07,32.0,Female,Lahore,Books,16,46269.84,False
4,CUST_1004,2023-01-09,60.0,Female,Karachi,Electronics,4,45996.23,False
5,CUST_1005,2023-01-11,25.0,Female,Lahore,Electronics,18,13023.01,True
...,...,...,...,...,...,...,...,...,...
145,CUST_1145,2023-10-18,57.0,Male,Lahore,Books,26,17581.59,False
146,CUST_1146,2023-10-20,39.0,Female,Karachi,Clothing,12,17707.15,False
147,CUST_1147,2023-10-22,NaN,Male,Lahore,Electronics,13,2074.33,False
148,CUST_1148,2023-10-24,44.0,Male,Karachi,Electronics,13,27661.41,False
149,CUST_1149,2023-10-26,52.0,Female,Lahore,Books,29,26953.96,True

In [137]:
val = df['Age'].median()
df['Age'] = df['Age'].fillna(val)

df['Total_Spent'] = df['Total_Spent'].fillna(df['Total_Spent'].mean())
df

,Customer_ID,Join_Date,Age,Gender,City,Category,Order_Count,Total_Spent,Is_VIP
1,CUST_1001,2023-01-03,56.0,Male,Peshawar,Home,17,16472.98,False
2,CUST_1002,2023-01-05,46.0,Female,Peshawar,Electronics,3,2648.34,True
3,CUST_1003,2023-01-07,32.0,Female,Lahore,Books,16,46269.84,False
4,CUST_1004,2023-01-09,60.0,Female,Karachi,Electronics,4,45996.23,False
5,CUST_1005,2023-01-11,25.0,Female,Lahore,Electronics,18,13023.01,True
...,...,...,...,...,...,...,...,...,...
145,CUST_1145,2023-10-18,57.0,Male,Lahore,Books,26,17581.59,False
146,CUST_1146,2023-10-20,39.0,Female,Karachi,Clothing,12,17707.15,False
147,CUST_1147,2023-10-22,41.0,Male,Lahore,Electronics,13,2074.33,False
148,CUST_1148,2023-10-24,44.0,Male,Karachi,Electronics,13,27661.41,False
149,CUST_1149,2023-10-26,52.0,Female,Lahore,Books,29,26953.96,True

In [138]:
dt = pd.to_datetime(df['Join_Date'])
year = df['Join_Date'].dt.year
month = df['Join_Date'].dt.month

df['Join_Year'] = year
df['Join_Month'] = month
df

,Customer_ID,Join_Date,Age,Gender,City,Category,Order_Count,Total_Spent,Is_VIP,Join_Year,Join_Month
1,CUST_1001,2023-01-03,56.0,Male,Peshawar,Home,17,16472.98,False,2023,1
2,CUST_1002,2023-01-05,46.0,Female,Peshawar,Electronics,3,2648.34,True,2023,1
3,CUST_1003,2023-01-07,32.0,Female,Lahore,Books,16,46269.84,False,2023,1
4,CUST_1004,2023-01-09,60.0,Female,Karachi,Electronics,4,45996.23,False,2023,1
5,CUST_1005,2023-01-11,25.0,Female,Lahore,Electronics,18,13023.01,True,2023,1
...,...,...,...,...,...,...,...,...,...,...,...
145,CUST_1145,2023-10-18,57.0,Male,Lahore,Books,26,17581.59,False,2023,10
146,CUST_1146,2023-10-20,39.0,Female,Karachi,Clothing,12,17707.15,False,2023,10
147,CUST_1147,2023-10-22,41.0,Male,Lahore,Electronics,13,2074.33,False,2023,10
148,CUST_1148,2023-10-24,44.0,Male,Karachi,Electronics,13,27661.41,False,2023,10
149,CUST_1149,2023-10-26,52.0,Female,Lahore,Books,29,26953.96,True,2023,10

In [139]:
df['Avg_Order_Value'] = df['Total_Spent']/df['Order_Count']
df

,Customer_ID,Join_Date,Age,Gender,City,Category,Order_Count,Total_Spent,Is_VIP,Join_Year,Join_Month,Avg_Order_Value
1,CUST_1001,2023-01-03,56.0,Male,Peshawar,Home,17,16472.98,False,2023,1,968.998824
2,CUST_1002,2023-01-05,46.0,Female,Peshawar,Electronics,3,2648.34,True,2023,1,882.780000
3,CUST_1003,2023-01-07,32.0,Female,Lahore,Books,16,46269.84,False,2023,1,2891.865000
4,CUST_1004,2023-01-09,60.0,Female,Karachi,Electronics,4,45996.23,False,2023,1,11499.057500
5,CUST_1005,2023-01-11,25.0,Female,Lahore,Electronics,18,13023.01,True,2023,1,723.500556
...,...,...,...,...,...,...,...,...,...,...,...,...
145,CUST_1145,2023-10-18,57.0,Male,Lahore,Books,26,17581.59,False,2023,10,676.215000
146,CUST_1146,2023-10-20,39.0,Female,Karachi,Clothing,12,17707.15,False,2023,10,1475.595833
147,CUST_1147,2023-10-22,41.0,Male,Lahore,Electronics,13,2074.33,False,2023,10,159.563846
148,CUST_1148,2023-10-24,44.0,Male,Karachi,Electronics,13,27661.41,False,2023,10,2127.800769
149,CUST_1149,2023-10-26,52.0,Female,Lahore,Books,29,26953.96,True,2023,10,929.446897

In [140]:
df['High_Value_Customer'] = df['Avg_Order_Value'] > 2500
df

,Customer_ID,Join_Date,Age,Gender,City,Category,Order_Count,Total_Spent,Is_VIP,Join_Year,Join_Month,Avg_Order_Value,High_Value_Customer
1,CUST_1001,2023-01-03,56.0,Male,Peshawar,Home,17,16472.98,False,2023,1,968.998824,False
2,CUST_1002,2023-01-05,46.0,Female,Peshawar,Electronics,3,2648.34,True,2023,1,882.780000,False
3,CUST_1003,2023-01-07,32.0,Female,Lahore,Books,16,46269.84,False,2023,1,2891.865000,True
4,CUST_1004,2023-01-09,60.0,Female,Karachi,Electronics,4,45996.23,False,2023,1,11499.057500,True
5,CUST_1005,2023-01-11,25.0,Female,Lahore,Electronics,18,13023.01,True,2023,1,723.500556,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,CUST_1145,2023-10-18,57.0,Male,Lahore,Books,26,17581.59,False,2023,10,676.215000,False
146,CUST_1146,2023-10-20,39.0,Female,Karachi,Clothing,12,17707.15,False,2023,10,1475.595833,False
147,CUST_1147,2023-10-22,41.0,Male,Lahore,Electronics,13,2074.33,False,2023,10,159.563846,False
148,CUST_1148,2023-10-24,44.0,Male,Karachi,Electronics,13,27661.41,False,2023,10,2127.800769,False
149,CUST_1149,2023-10-26,52.0,Female,Lahore,Books,29,26953.96,True,2023,10,929.446897,False

In [141]:
gc = df.groupby('City')
print('------- Customer Count --------\n',gc['Customer_ID'].count())

avg = gc['Total_Spent'].mean()
print('------- Average Total Spent -------\n', avg)

maxCount = gc['Order_Count'].max()
print('------- Maximum Order Count -------\n', maxCount)

------- Customer Count --------
 City
Islamabad    30
Karachi      29
Lahore       41
Peshawar     37
Name: Customer_ID, dtype: int64
------- Average Total Spent -------
 City
Islamabad    24533.950045
Karachi      27379.049851
Lahore       25955.630521
Peshawar     21828.029613
Name: Total_Spent, dtype: float64
------- Maximum Order Count -------
 City
Islamabad    28
Karachi      29
Lahore       29
Peshawar     29
Name: Order_Count, dtype: int32

In [142]:
pivot = pd.pivot_table(df, index='Category', columns='Is_VIP', values='Total_Spent', aggfunc='sum')
pivot

Is_VIP              False         True
Category
Books        773581.96568  229891.67000
Clothing     687625.76136   99350.15784
Electronics  806814.38568  190542.61000
Home         439472.59568  174549.74784

In [143]:
top5 = (df[df['Category'].isin(['Electronics', 'Clothing'])]
        .sort_values('Total_Spent', ascending=False)
        .head(5))
top5[['Customer_ID', 'City', 'Category', 'Total_Spent']]

    Customer_ID       City     Category  Total_Spent
103   CUST_1103    Karachi  Electronics     49032.90
17    CUST_1017  Islamabad  Electronics     47955.77
40    CUST_1040   Peshawar  Electronics     47056.33
43    CUST_1043  Islamabad     Clothing     45999.24
4     CUST_1004    Karachi  Electronics     45996.23

In [144]:
vip = df[(df['Is_VIP']) & (df['City'].isin(['Karachi', 'Lahore']))]
vip.groupby('City')['Order_Count'].agg(['count', 'mean'])

         count       mean
City
Karachi      7  16.285714
Lahore       7  17.428571

In [145]:
print("Avg spend by VIP:\n", df.groupby('Is_VIP')[['Total_Spent', 'Order_Count', 'Avg_Order_Value']].mean())
print("\nRevenue by city:\n", df.groupby('City')['Total_Spent'].sum().sort_values(ascending=False))

print("\nRevenue by category:\n", df.groupby('Category')['Total_Spent'].sum().sort_values(ascending=False))
print("\nHigh-value share: %.1f%%" % (df['High_Value_Customer'].mean() * 100))

Avg spend by VIP:
          Total_Spent  Order_Count  Avg_Order_Value
Is_VIP
False   24839.400994    16.036697      2935.691755
True    24797.649489    16.107143      2184.371894

Revenue by city:
 City
Lahore       1.064181e+06
Peshawar     8.076371e+05
Karachi      7.939924e+05
Islamabad    7.360185e+05
Name: Total_Spent, dtype: float64

Revenue by category:
 Category
Books          1.003474e+06
Electronics    9.973570e+05
Clothing       7.869759e+05
Home           6.140223e+05
Name: Total_Spent, dtype: float64

High-value share: 25.5%

**Insights**
- Lahore is the largest revenue source (≈ 1.06M, 41 customers), while Karachi has the highest average spend per customer (27,379).
- VIP and non-VIP customers spend almost the same on average (24,798 vs 24,839), and VIPs have a lower Avg_Order_Value (2,184) than non-VIPs (2,936).
- Books (≈ 1.00M) and Electronics (≈ 997K) lead in revenue, with Home last (≈ 614K); in every category, most of the revenue comes from non-VIP customers.